### ISSUE TITLE
Emulator issues on Raspberry Pi

### ISSUE THREAD

**Issue by borospeti** [istvan-v/ep128emu#5]
ep128emu compiles and seemingly runs without errors on a Raspberry Pi (Model 3 B, Raspbian), but none of the virtual machines works, regardless of config (I have tried TVC, ZX and EP). The same setup worked fine on a x86_64 Debian system.
I suspect there are some issues due to differences between the x86 and the Arm architecture. Memory alignment, integer sizes, signed vs unsigned char, possibly endiannes (Arm supports both but Pi uses LE) comes to mind. I will look into the code to see if I can identify the culprit, but it would be useful if you had some ideas or pointers where to start.

**Comment by borospeti** [comment]
Fixed by pull request #6 .

**Comment by istvan-v** [comment]
Thanks, the changes have been merged.
